# Generated by Django 5.1.1 on 2024-09-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_book_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Unknown Author', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='book_category',
            field=models.CharField(default='Unknown book_category', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='Unknown language', max_length=30),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
